name: Build

on:
  push:
    branches: [main, zig-master]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest,
        ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Build
        run: zig build -Doptimize=ReleaseSmall

      - name: Unit Test BSPs
        run: zig build run-bsp-tests -Doptimize=ReleaseSmall

      - name: Dry run packaging
        run: |
          MICROZIG_VERSION=$(zig build package -- get-version)
          zig build package -- http://localhost:8000
          python3 -m http.server 8000 --directory boxzer-out > http.log &

          cd tools/package-test
          zig fetch --save=microzig http://localhost:8000/microzig-${MICROZIG_VERSION}.tar.gz
          zig build -Doptimize=ReleaseSmall
          zig build run-bsp-tests=ReleaseSmall

          # clean up server
          jobs -p | xargs kill

          #- name: Upload HTTP logs
          #  uses: actions/upload-artifact@v3
          #  with:
          #    name: http.log
          #    path: http.log
